//
// Created by axeld on 01/12/2021.
//

#ifndef EIGENVALUE_PROJECT_GENERALEIGENSOLVER_H
#define EIGENVALUE_PROJECT_GENERALEIGENSOLVER_H


class GeneralEigenSolver {

};


#endif //EIGENVALUE_PROJECT_GENERALEIGENSOLVER_H
